#!/usr/bin/env python3
"""Import alerts generated by the UI converter into the app DB via inserir_alertas.

Usage:
  python -m scripts.import_alerts -i "dados_simulados/gerados_ui/*_alerts_*.jsonl" [--commit]

By default runs as a dry-run and prints a preview. Use --commit to persist.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List

import pandas as pd


def detect_input_paths(pattern: str) -> list[Path]:
    p = Path('.').resolve()
    if any(ch in pattern for ch in ['*', '?', '[']):
        matches = list(p.glob(pattern))
    else:
        matches = [p.joinpath(pattern)]
    if not matches:
        raise FileNotFoundError(f"No files match pattern: {pattern}")
    return matches


def read_jsonl(path: Path) -> Iterable[Dict[str, Any]]:
    with open(path, 'r', encoding='utf-8') as fh:
        for ln in fh:
            ln = ln.strip()
            if not ln:
                continue
            yield json.loads(ln)


def read_csv(path: Path) -> Iterable[Dict[str, Any]]:
    df = pd.read_csv(path)
    for rec in df.to_dict(orient='records'):
        yield rec


def normalize_iso(ts: str) -> str:
    # parse a variety of ISO-like strings and produce YYYY-MM-DDTHH:MM:SS
    if ts is None:
        raise ValueError('timestamp is None')
    try:
        dt = pd.to_datetime(ts)
        return dt.floor('s').strftime('%Y-%m-%dT%H:%M:%S')
    except Exception:
        # fallback: attempt naive parse
        try:
            dt = datetime.fromisoformat(str(ts)[:19])
            return dt.strftime('%Y-%m-%dT%H:%M:%S')
        except Exception as exc:
            raise ValueError(f"Could not parse timestamp: {ts}") from exc


def map_record_to_alert(rec: Dict[str, Any]) -> Dict[str, Any]:
    # Input shape may be frontend-shaped (id, patientName, lastRepositioning, nextRepositioning, riskLevel, status)
    # We need to produce DAO-shaped alert dict: paciente_id, inicio, tipo, perfil, janela_min, status
    paciente = rec.get('patientName') or rec.get('paciente_id') or None
    if not paciente:
        # try parsing from id
        rid = rec.get('id') or ''
        if isinstance(rid, str) and '_' in rid:
            paciente = rid.split('_')[0]
        else:
            paciente = 'PAC-0001'

    inicio_raw = rec.get('lastRepositioning') or rec.get('inicio') or rec.get('timestamp')
    inicio = normalize_iso(inicio_raw)

    next_raw = rec.get('nextRepositioning')
    janela_min = 0
    if next_raw:
        try:
            dt_ini = pd.to_datetime(inicio)
            dt_next = pd.to_datetime(next_raw)
            janela_min = int(round((dt_next - dt_ini).total_seconds() / 60.0))
            if janela_min < 0:
                janela_min = 0
        except Exception:
            janela_min = 0

    # map riskLevel -> perfil
    risk = str(rec.get('riskLevel') or '').lower()
    perfil_map = {'high': 'alto', 'medium': 'medio', 'low': 'baixo', 'alto': 'alto', 'medio': 'medio', 'baixo': 'baixo'}
    perfil = perfil_map.get(risk, 'medio')

    # status mapping
    status_map = {'pending': 'aberto', 'acknowledged': 'reconhecido', 'completed': 'fechado', 'pending': 'aberto'}
    status = status_map.get(str(rec.get('status') or '').lower(), 'aberto')

    alerta = {
        'paciente_id': paciente,
        'inicio': inicio,
        'tipo': 'imobilidade',
        'perfil': perfil,
        'janela_min': int(janela_min),
        'status': status,
    }
    return alerta


def load_alerts_from_files(paths: List[Path]) -> List[Dict[str, Any]]:
    alerts: List[Dict[str, Any]] = []
    for p in paths:
        if p.suffix.lower() == '.jsonl':
            for rec in read_jsonl(p):
                alerts.append(map_record_to_alert(rec))
        elif p.suffix.lower() in {'.csv', '.tsv'}:
            for rec in read_csv(p):
                alerts.append(map_record_to_alert(rec))
        else:
            # attempt to autodetect by content
            text = p.read_text(encoding='utf-8')
            if '\n' in text and text.lstrip().startswith('{'):
                for rec in read_jsonl(p):
                    alerts.append(map_record_to_alert(rec))
            else:
                for rec in read_csv(p):
                    alerts.append(map_record_to_alert(rec))
    return alerts


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description='Import alerts JSONL/CSV into DB via inserir_alertas')
    parser.add_argument('--input', '-i', required=True, help='Input file path or glob pattern')
    parser.add_argument('--db-path', '-d', default=None, help='Path to DB (defaults to application DB)')
    parser.add_argument('--commit', action='store_true', help='If set, persist alerts into DB. Otherwise runs as dry-run.')
    args = parser.parse_args(argv)

    # import here to avoid importing app heavy modules on dry-run help
    from interface.api import DB_PATH as APP_DB_PATH
    from interface.dao import inserir_alertas, ensure_minimal_paciente_ficha

    db_path = args.db_path or APP_DB_PATH

    paths = detect_input_paths(args.input)
    print(f"Found {len(paths)} input file(s):")
    for p in paths:
        print(' -', p)

    alerts = load_alerts_from_files(paths)
    print(f"Parsed {len(alerts)} alerts (after mapping).")

    # show preview of first few
    preview_n = min(5, len(alerts))
    if preview_n:
        print('\nPreview:')
        for a in alerts[:preview_n]:
            print(json.dumps(a, ensure_ascii=False))

    if not args.commit:
        print('\nDRY-RUN mode (no DB changes). Use --commit to persist into DB.')
        return 0

    # persist
    # ensure minimal fichas for referenced pacientes so frontend can show name/cama
    pacientes = {str(a.get('paciente_id')) for a in alerts if a.get('paciente_id')}
    for pid in pacientes:
        try:
            ensure_minimal_paciente_ficha(db_path, pid)
        except Exception:
            # non-fatal: continue with insertion even if ensuring ficha fails
            pass

    inserted = inserir_alertas(db_path, alerts)
    print(f"Inserted {inserted} new alerts into DB '{db_path}'.")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
