name: Run Python Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show files (debug)
        run: |
          pwd
          ls -la
          if [ -f requirements.txt ]; then echo "=== requirements.txt ==="; cat requirements.txt; fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Fallback para garantir que testes rodam
          pip install pandas pytest || true

      - name: Run tests
        run: pytest -q
